# replace .war with .jar or .ear if needed
name: Whitesource Prioritize Java with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: WhiteSource Unified Agent Scan
      env:
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
        WS_PRODUCTNAME: GH_${{github.event.repository.name}}
        WS_PROJECTNAME: ${{github.ref}}_Prioritize
        WS_ENABLEIMPACTANALYSIS: true
        WS_REQUIREKNOWNSHA1: false
        WS_RESOLVEALLDEPENDENCIES: false
        WS_MAVEN_RESOLVEDEPENDENCIES: true
        WS_MAVEN_AGGREGATEMODULES: true
        WS_FILESYSTEMSCAN: false
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        WARFILE=$(find ./ -type f -wholename "*/target/*.war")
        export WS_FILESYSTEMSCAN=false
        java -jar wss-unified-agent.jar -appPath $WARFILE -d ./
        
